RIDE_REQUESTED = "REQUESTED"
RIDE_ACCEPTED = "ACCEPTED"
RIDE_DRIVER_ARRIVING = "DRIVER_ARRIVING"
RIDE_STARTED = "STARTED"
RIDE_COMPLETED = "COMPLETED"
RIDE_CANCELLED = "CANCELLED"

DEFAULT_DRIVER_RADIUS_KM = 5