# Generated by Django 6.1 on 2026-08-17 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_passeng_db0d3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_driver__850520_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_status__c37074_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='rides_ride_request_c8cf74_idx',
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', 'status'], name='rides_ride_passeng_5e3e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_ride_driver__de79ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_ride_status__8f6a42_idx'),
        ),
    ]
