# Generated by Django 6.1 on 2026-08-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_rides_ride_passeng_db0d3e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rides.driverprofile'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
