# Generated by Django 6.1 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_location_driver_location_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='availability_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='ONLINE', max_length=10),
        ),
    ]
