# Generated by Django 6.1 on 2026-08-20 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_location_availability_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('RIDE', 'Ride'), ('DRIVER', 'Driver'), ('COMPLETED', 'Completed'), ('REMINDER', 'Reminder')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='rides_notif_user_id_4ce912_idx'), models.Index(fields=['user', 'created_at'], name='rides_notif_user_id_627fe9_idx'), models.Index(fields=['notification_type'], name='rides_notif_notific_d85800_idx')],
            },
        ),
    ]
