# Generated by Django 6.1 on 2026-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
