# Generated by Django 6.1 on 2026-09-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_available', 'availability_status'], name='rides_locat_is_avai_5ab530_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', '-created_at'], name='rides_ride_passeng_c45f16_idx'),
        ),
    ]
