# Generated by Django 6.1 on 2026-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
