# Generated by Django 6.1 on 2026-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_unique_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
